### PR TITLE
Datadog

### PR DESCRIPTION
**Pull request by meaganacombs**
see staging service page in datadog [here](https://app.datadoghq.com/apm/services/elevation/operations/web.request/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&env=stage-elevation&fromUser=false&groupMapByOperation=null&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%29%2Cversion%3A%211%29&view=spans&start=1717614005754&end=1717617605754&paused=false)

I needed to set one env var on the datadog agent container and will need to do this in prod too
```
       {
                    "name": "DD_CMD_PORT",
                    "value": "6001"
                },
```

### CODE REVIEW

**Comment by benjaminblack** [comment]
I can implement what the DataDog [docs say to do](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs/), if you don't object

**Comment by meaganacombs** [comment]
> I can implement what the DataDog [docs say to do](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/nodejs/), if you don't object

[this](https://github.com/trailbehind/elevation-service/blob/7330f0131e38e6099a0872e9772df61faeec1988/package.json#L8) works - traces are being collected and is one of the options in the docs - but yeah I just wanted to avoid typescript 😅 if you'd prefer the `tracer.ts` approach thats fine with me!

**Comment by benjaminblack** [comment]
OK, that's all good. 

It looks like `server.ts` got committed with nothing but formatting changes -- can you revert that to master?

**Comment by meaganacombs** [comment]
> OK, that's all good.
> 
> It looks like `server.ts` got committed with nothing but formatting changes -- can you revert that to master?

yep

**Review by andharris — APPROVED** [review]

**Review by benjaminblack — APPROVED** [review]

**Pull request merged**
